apiVersion: v1
kind: Pod
metadata:
    name: gpu-pod
spec:
    containers:
        - name: gpu-container
          image: traininghost/pipelinegpuimage:latest
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
          resources:
            limits:
              nvidia.com/gpu: 1
    restartPolicy: Never
